server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:robotrix_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      keepalive-time: 30000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: robotrixapp@gmail.com
    password: ijko jalm auwx ykhw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: dGhpcy1pcy1hLXNlY3VyZS1hbmQtc3VwZXItc2VjcmV0LWtleS1mb3Itam9zZS1qd3QtdG9rZW4tc2lnbmluZw==
  expiration: 3153600000000 # 100 years (permanent session until manual logout)

app:
  storage:
    type: ${STORAGE_TYPE:local} # "local" for dev, "s3" for prod
    local-dir: ${STORAGE_LOCAL_DIR:./uploads}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:robotrix-prod-image-559947225352-ap-south-1-an}
    region: ${AWS_REGION:ap-south-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    endpoint: ${AWS_S3_ENDPOINT:}

